/* eslint-disable import/no-extraneous-dependencies */
import gql from 'graphql-tag';

export const GET_USER_POSTS = gql`
  query GetUserPosts($uid: ID!) {
    userPosts(id: $uid) {
      favourite_post{
      id
      title
      content
      slug
      price
      status
      isNegotiable
      propertyType
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        id
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        id
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        id
        url
      }
      createdAt
      updatedAt
    }
      listed_posts{
       id
      title
      content
      slug
      price
      status
      isNegotiable
      propertyType
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        id
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        id
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        id
        url
      }
      categories{
        id
        slug
        name
        image
        {
          id
          url
        }
      }
      reviews{
        reviewID
        reviewOverall
      }
      createdAt
      updatedAt
    }
  }
  }
`;
export const GET_HEART = gql`
  query GetUserPosts($uid: ID!) {
    userPosts(id: $uid) {
      favourite_post{
      id
      title
      content
      slug
      price
      status
      isNegotiable
      propertyType
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        id
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        id
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        id
        url
      }
      createdAt
      updatedAt
      }
    }
  }
`;
export const GET_USER_INFO = gql`
query GetUserInfo($id: ID!){
  getUserInfo(id:$id){
    id
    first_name
    last_name
    role
    stripeId
    date_of_birth
    gender
    gallery{
      url
      uid
      id
    }
    agent_location {
      lat
      lng
      formattedAddress
      zipcode
      city
      state_long
      state_short
      country_long
      country_short
    }
    favourite_post{
      id
      title
      content
      slug
      price
      status
      isNegotiable
      propertyType
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        id
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        id
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        id
        url
      }
      createdAt
      updatedAt
    }
      listed_posts{
       id
      title
      content
      slug
      price
      status
      isNegotiable
      propertyType
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        id
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        id
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        id
        url
      }
      createdAt
      updatedAt
    }
    social_profile{
      facebook
      linkedIn
      twitter
      instagram
    }
    cellNumber
    content
    profile_pic_main
    cover_pic_main
  }
}
`;
export const GET_ALL_HOTELS = gql`
    query GetAllHotels($type: String, $search: SearchInput, $amenities: AmenitiesSearchInput, $property: [String], $location: LocationInput){
    getAllHotels(type:$type, search: $search, amenities: $amenities, property: $property, location: $location){
      id
      title
      content
      slug
      price
      agentName
      agentEmail
      peopleLiked{
        id
      }
      status
      isNegotiable
      propertyType
      image{
       url
       thumb_url
      }
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        url
      }
      reviews{
        reviewID
        reviewOverall
      }
      createdAt
      updatedAt
    }
  }
`;
export const GET_FILTERED_HOTELS = gql`
  query GetFilteredHotels($search: SearchInput, $amenities: AmenitiesSearchInput, $property: [String]){
      getFilteredHotels(search: $search, amenities: $amenities, property: $property){
         id
      title
      content
      slug
      price
      agentName
      agentEmail
      status
      isNegotiable
      propertyType
      image{
       url
       thumb_url
      }
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        url
      }
      createdAt
      updatedAt
      }
  }
`;
export const GET_HOTEL_INFO = gql`
  query GetHotelInfo($id: ID!){
    getHotelInfo(id: $id){
      id
      title
      content
      slug
      price
      agentName
      agentEmail
      agentId
      status
      isNegotiable
      propertyType
      image{
       url
       thumb_url
      }
      condition
      rating
      ratingCount
      contactNumber
      termsAndCondition
      amenities{
        guestRoom
        bedRoom
        wifiAvailability
        parkingAvailability
        poolAvailability
        airCondition
        extraBedFacility
      }
      location{
        lat
        lng
        formattedAddress
        zipcode
        city
        state_long
        state_short
        country_long
        country_short
      }
      gallery{
        url
      }
      reviews{
        reviewID
        reviewTitle
        reviewText
        sortOfTrip
        reviewAuthorId{
          id
        }
        reviewAuthorFirstName
        reviewAuthorLastName
        reviewAuthorEmail
        reviewOverall
        reviewAuthorPic
        reviewedHotelId
        reviewTips
        reviewPics{
           url
        }
        reviewDate
        reviewOptional{
          option 
          optionField
        }
        reviewFields{
            rating 
            ratingFieldName
          }
      }
      peopleReviewed{
        id
      }
      peopleLiked{
        id
      }
      createdAt
      updatedAt
    }
  }
`;
export const GET_HOTEL_REVIEWS = gql`
  query GetHotelReviews($id: ID!){
    getHotelReviews(id:$id){
        reviewID
        reviewTitle
        reviewText
        sortOfTrip
        reviewAuthorId{
          id
        }
        reviewAuthorFirstName
        reviewAuthorLastName
        reviewAuthorEmail
        reviewOverall
        reviewAuthorPic
        reviewedHotelId
        reviewTips
        reviewPics{
           url
        }
        reviewDate
        reviewOptional{
          option 
          optionField
        }
        reviewFields{
            rating 
            ratingFieldName
          }
    }
  }
`;
export const GET_HOTEL_MANAGER_COUPONS = gql`
  query  {
    getHotelManagerCoupons{
      couponId
      couponName
      couponDescription
      couponType
      couponValue
      couponQuantity
      couponStartDate
      couponEndDate
      couponRange
      couponTarget{
        slug
        id
      }
      createdAt
      updatedAt
    }
  }
`;
export const GET_HOTEL_COUPONS = gql`
    query GetHotelCoupons($id: ID!){
      getHotelCoupons(id: $id){
        couponId
        couponName
        couponDescription
        couponAuthor{
         email
        }
        couponAuthorId
        couponType
        couponValue
        couponQuantity
        couponStartDate
        couponEndDate
        couponTarget{
        id
        slug
        title
      }
        createdAt
        updatedAt
       }
     }
`;
export const GET_HOTEL_REVIEWS_LIKE_DISLIKE = gql`
      query GetReviewLikeDislike($id: ID!){
        getHotelInfo(id:$id){
        id
        reviews{
          peopleLiked {
            id
          }
          peopleDisliked {
            id
          }
        }
      }
    }
`;
export const GET_REVIEWS_LIKE_DISLIKE = gql`
    query GetReviewsLikeDislike($id: ID!){
      getReviewsLikeDislike(id:$id){
          reviewID
          peopleLiked {
          id
          }
          peopleDisliked {
          id
          }
      }
    }
`;
export const GET_USER_NOTIFICATION = gql`
 query GetUserNotifcation($id: ID!){
      getUserNotification(id:$id){
        reviewTitle
        reviewText
        reviewAuthorName
        reviewedHotelName
        peopleReviewedQuantity
        query
        reviewAuthorProfilePic
        read
      }
    }
`;
export const GET_USER_UNREAD_NOTIFICATION_NUMBER = gql`
query GetUserUnreadNotification($id: ID!){
  getUserUnreadNotification(id:$id){
    unreadNotification
  }
}
    `;
export const GET_TRANSACTIONS_HAVING = gql`
    query GetTransactionsHaving($orderBy: String){
        getTransactionsHaving(orderBy: $orderBy){
            TXID
            transactionSecretKey
            transactionHotelName
            transactionHotelId
            transactionHotelManager{
                first_name
                last_name
                email
                cellNumber
            }
            transactionHotelManagerId
            transactionHotelType
            transactionPrice
            transactionAuthorId
            transactionAuthorName
            transactionAuthorEmail
            transactionAuthorContactNumber
            transactionAuthorSpecial
            transactionAuthorNote
            transactionLocationLat
            transactionLocationLng
            transactionLocationFormattedAddress
            transactionRoom
            transactionGuest
            transactionRange
            transactionStatus
            transactionCoupon
            transactionCouponType
            transactionCouponValue
            transactionStartDate
            transactionEndDate
            transactionStripeId
        }
    }
`;
export const GET_TRANSACTION_DETAILS = gql`
    query GetTransactionDetails($transactionSecretKey: String){
      getTransactionDetails(transactionSecretKey: $transactionSecretKey){
            transactionLocationLa
      }
    }
`;
export const GET_TOTAL_UNREAD_TRANSACTIONS = gql`
    query GetTotalUnreadTransactions{
      getTotalUnreadTransactions{
          uncheckTransactions {
          totalPrice
          totalTransactions
        }
      }
    }
`;
export const GET_VENDOR_STRIPE_ID = gql`
  query GetVendorStripeId($id: String){
    getVendorStripeId(id: $id){
      stripeId
    }
  }
`;
